import React from 'react'

export default function PrivacyPolicy() {
    return (
        <section className="privacy-policy grid__parallax dark">
            <div className="container">
                <div className="privacy-policy-content">
                    <div className="intro">
                        <h1 className='h3'>Privacy Policy</h1>
                        <p>At Clear Digital&#44; we are committed to protecting and respecting your privacy.</p>
                        <p>This Privacy Notice and Terms of Use (&quot;Notice&quot;) explains when and why we collect personal information about people who visit our website. It describes how we use the data we collect&#44; the conditions under which we may disclose it to others and how we keep it secure.</p>
                        <p>We may change this Notice from time to time&#44; so please check this page occasionally to ensure that you&#39;re happy with any changes. By using our website&#44; you&#39;re agreeing to be bound by this Notice.</p>
                        <p>Any questions regarding this Notice and our privacy practices should be sent by email to info@cleardigital.com&#44; or by writing to 1570 The Alameda&#44; Ste 330&#44; San Jose&#44; CA 95126.</p>
                    </div>
                    <h5>Definitions</h5>
                    <p>Clear Digital&#44; Inc. (&quot;Clear Digital&#44;&quot; &quot;us&quot;&#44; &quot;we&quot;&#44; or &quot;our&quot;) operates the website https://www.cleardigital.com (the &quot;Site&quot;).</p>
                    <h6>Personal Data</h6>
                    <p>Personal Data means data about a living individual who can be identified from that data (or from those and other information either in our possession or likely to come into our possession).</p>
                    <h6>Usage Data</h6>
                    <p>Usage Data is data collected automatically either generated by the use of the Site or from the Site infrastructure itself (for example&#44; the duration of a page visit).</p>
                    <h6>Cookies</h6>
                    <p>Cookies are small pieces of data stored on a user&#39;s device.</p>
                    <h6>Data Controller</h6>
                    <p>Data Controller means a person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are&#44; or are to be&#44; processed. For the purpose of this Notice and Site&#44; we are a Data Controller of your data.</p>
                    <h6>Data Processor (or Service Providers)</h6>
                    <p>Data Processor (or Service Provider) means any person (other than an employee of the Data Controller) who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</p>
                    <h6>Data Subject</h6>
                    <p>Data Subject is any living individual who is the subject of Personal Data.</p>
                    <h6>User</h6>
                    <p>The User is the individual using our Site. The User corresponds to the Data Subject&#44; who is the subject of Personal Data.</p>
                    <h6>Information Collection And Use</h6>
                    <p>We collect several different types of information for various purposes to provide and improve our Site to you</p>
                    <h6>Personal Data</h6>
                    <p>While using our Site&#44; we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (&quot;Personal Data&quot;). Personally identifiable information may include:</p>
                    <ul>
                        <li>IP Address</li>
                        <li>Usage Data</li>
                        <li>Email address</li>
                        <li>Phone number</li>
                        <li>First name and last name</li>
                        <li>Details related to the nature/reason of your inquiry</li>
                        <li>Your current company and job title</li>
                        <li>Details about your company:</li>
                        <li className='ml-[3rem]'>{`{{PROGRESSIVE PROFILE FIELDS}}`}</li>
                    </ul>
                    <p>You may use our Site without providing any Personal Data&#44; or agreeing to the terms of this Notice. By doing so&#44; some of the content and functionality of the Site will be unavailable.</p>
                    <p>We may use your Personal Data to contact you with content&#44; upcoming events&#44; and new services and other information that may be of interest to you. Where required by law&#44; you must first opt-in to receive such communications from us. You may opt out of these communications from us at any time by following the unsubscribe link or instructions provided in any email we send or by contacting us directly.</p>
                </div>
            </div>
        </section>
    )
}
